[project]
name = "Rabbit-in-a-Blender"
version = "0.0.10"
authors = [
  { name="Lammertyn Pieter-Jan", email="pieter-jan.lammertyn@azdelta.be" },
  { name="Dupulthys Stijn", email="Stijn.Dupulthys@azdelta.be" }
]
description = "An ETL pipeline to transform your EMP data to OMOP."
readme = "README.md"
license = { file="LICENSE" }
keywords= ["OMOP", "CDM", "common data model", "OHDSI"]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    'backoff >= 2.1.2',
    'connectorx >= 0.3.0',
    'polars >= 0.14.9',
    'jinja2 >= 3.1.2',
    'google-cloud-bigquery >= 3.3.2',
    'google-cloud-storage >= 2.5.0',
    'simple-ddl-parser >= 0.27.0'
]

[project.urls]
"Homepage" = "https://radar-azdelta.github.io/Rabbit-in-a-Blender/"
"Source Code" = "https://github.com/RADar-AZDelta/Rabbit-in-a-Blender"
"Bug Tracker" = "https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/issues"

[project.scripts]
riab = "riab:cli"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.json", "*.sql", "*.jinja"]